### ISSUE TITLE
Correct and complete instruction format doc

### ISSUE THREAD

**Issue by rhinton** [archntu/idea#1]
It appears the published papers on iDEA use a different instruction format.  In particular, the opcode has moved to the MSBs, and the conditions/flags to the LSBs.  I am putting together a preliminary guess at the instruction format at the wiki page [[InstructionFormat]].  Please correct any mistakes and fill out missing information.  Thanks!

**Comment by hycheah** [comment]
Hi, will check when I get back

**Comment by rhinton** [comment]
Great, thanks.  I guess the real question is whether there is any detailed architecture information on the latest implementation here in git.  For example, what are the opcodes?  I've spent a little time toward creating an LLVM backend for iDEA, but it's too much work to guess from the source code.

I love the idea of a small, simple, fast (high MHz) processor.  I have some suggestions for register forwarding (of a sort) and I/O.  I agree that ideally the processor should be a thin wrapper around some BRAMs for instruction and data memory, LUT RAM for registers, and DSP48 for ALU and most everything else.

**Comment by hycheah** [comment]
The idea instruction set has undergone many changes since its first
version. For compiler compatibility reasons, I adopted the MIPS I
instructions set. You could find the reference from this link:
http://opencores.org/project,plasma,opcodes

You can also find the list of supported instructions from the defines.v
file in the rtl/ folder

**Comment by rhinton** [comment]
Do you have any numbers on the change (if any) in achievable frequency and
size when switching to the MIPS instruction set?  I like the idea of using
a backend like LLVM to move as much of the complexity as possible into the
compiler.  In other words, minimize the in-logic muxing in the FPGA. 
Tailor the instruction layouts to the DSP48 inputs.  Make the HDL as
simple as possible.  Make the machine as consistent as possible in the
FPGA fabric, and make the compiler deal with the resulting idiosyncrasies.

Can you point me to an earlier commit that has the instruction set as
described in your paper(s)?  Does it make sense to branch from this point
for my experiments?

Thanks!
- Ryan

**Comment by hycheah** [comment]
You could checkout the first few commits if you want the earlier version of
idea. The latest frequency is about ~480MHz
